### ISSUE TITLE
Error to Complie Diana Demo

### ISSUE THREAD

**Issue by otaviojava** [JNOSQL/diana-demos#5]
[ERROR] Failed to execute goal on project jsr363: Could not resolve dependencies for project org.jnosql.diana.demo:jsr363:war:1.0-SNAPSHOT: Failure to find org.jnosql.diana:hazelcast-driver:jar:0.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

**Comment by rafadelnero** [comment]
We solved this problem :)

**Comment by otaviojava** [comment]
@rafadelnero Thanks
